var favouriteColor = "Blue";
console.log(favouriteColor);
favouriteColor = "green";
console.log(favouriteColor);
var userName = "Aamir Khan Channa";
console.log(userName);
var age = 25;
console.log(age);
var isStudent = true;
console.log(isStudent);
